baseurl = "/"
languageCode = "en-us"
theme = "dotfiles"
paginate = 5
enableGitInfo = true
capitalizeListTitles = false

# Add support for embedding HTML in markdown files
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[languages]
  [languages.en]
    languageName = "English"
    title = "#!/matt/rathbun"
    subtitle = "Matt Rathbun's Personal Blog"
    owner = "Matt Rathbun"
    keywords = ""
    copyright = "&copy; 2020 Matt Rathbun"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "#!/matt/rathbun"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/mattbun"
        weight = 80
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "linkedin"
        url = "https://linkedin.com/in/matthewrathbun"
        weight = 90
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "/posts"
        url = "/posts"
        weight = 10

[frontmatter]
date = [":filename", ":default"]
