name: Hugo Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix develop --command make build

      - name: Create CNAME file
        run: cp CNAME public/CNAME

      - name: Publish to test branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages-test
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
